// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM_H_WVXvsr-ErYHYBqhAMpFlhgkxYvnU',
    appId: '1:688391814203:web:562547b350c7a0a851f01e',
    messagingSenderId: '688391814203',
    projectId: 'messenger-c84b0',
    authDomain: 'messenger-c84b0.firebaseapp.com',
    storageBucket: 'messenger-c84b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB93XW-bRK06RxMwpq1jUcb7Gm4hvjv4AI',
    appId: '1:688391814203:android:43cbf4d63456c73f51f01e',
    messagingSenderId: '688391814203',
    projectId: 'messenger-c84b0',
    storageBucket: 'messenger-c84b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMYTvyyhRZl_b6HYuS7vn7oI1oOYckXo4',
    appId: '1:688391814203:ios:b0dfd4f67fdd79bf51f01e',
    messagingSenderId: '688391814203',
    projectId: 'messenger-c84b0',
    storageBucket: 'messenger-c84b0.appspot.com',
    iosClientId: '688391814203-s0nbic64r42qpgof5ed1kfb0bfl7q3rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipssi2023montevrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMYTvyyhRZl_b6HYuS7vn7oI1oOYckXo4',
    appId: '1:688391814203:ios:b0dfd4f67fdd79bf51f01e',
    messagingSenderId: '688391814203',
    projectId: 'messenger-c84b0',
    storageBucket: 'messenger-c84b0.appspot.com',
    iosClientId: '688391814203-s0nbic64r42qpgof5ed1kfb0bfl7q3rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipssi2023montevrain',
  );
}
